POST http://localhost:8080/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "1234"
}
###
GET http://localhost:8080/auth/logout HTTP/1.1
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTMwODMzNTEsImV4cCI6MTcxMzA4Njk1MX0.16No6tc_ZC7BUNV23FAPEh_Cami5aZqPFseqcvlt6BE    

###
POST http://localhost:8080/auth/register HTTP/1.1
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "1234",
    "fullName": "Test"
}
###
GET http://localhost:8080/client/carwash HTTP/1.1
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTMwNDM1NTEsImV4cCI6MTcxMzA0NzE1MX0.WpDv2jWEi13mP7qMH6A0cgwiys3wOXa9t4YryW1gW2s
###
GET http://localhost:8080/client/carwash HTTP/1.1
Cookie: accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZXhwIjoxNzEyODcyOTIzfQ.IPkNkmJofOKpIUE59SFoxVrMwFInhoh8JcDblwI3N-A

### CREATE CARWASH
POST http://localhost:8080/admin/carwash HTTP/1.1
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQyMDQ5NDksImV4cCI6MTcxNDIwODU0OX0.AnHIQ2Gc7NyNIXktdGSTyzZ-cnOsA41C4hCR_wxY-5A

{
    "name": "CarWash4",
    "address": "Address",
    "latitude": 123.123,
    "longitude": 123.123,
    "active": true,
    "openTime": "08:00",
    "contact": "123456789"
}


### SEARCH CARWASH
GET http://localhost:8080/admin/carwash?searchString=&pageNumber=1&limit=10 HTTP/1.1
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQzMDI0OTMsImV4cCI6MTcxNDMwNjA5M30.zif-PulBxBLPJMCLnvw4rY6vHPhNJhYejE-t9a0OWj4

### UPDATE CARWASH
PATCH http://localhost:8080/admin/carwash HTTP/1.1
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQzMDI0OTMsImV4cCI6MTcxNDMwNjA5M30.zif-PulBxBLPJMCLnvw4rY6vHPhNJhYejE-t9a0OWj4

{
    "id": 4,
    "active": false
}

### DELETE CARWASH
DELETE http://localhost:8080/admin/carwash HTTP/1.1
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQyOTg4NjQsImV4cCI6MTcxNDMwMjQ2NH0.fL1jAQSCuq_j9644Gj03fuLpTUdrqYFL3P6OXoDxfPw
{
    "id": 3
}

### GET SERVICES BY CARWASH
GET http://localhost:8080/client/service?carWashID=3
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQyOTg4NjQsImV4cCI6MTcxNDMwMjQ2NH0.fL1jAQSCuq_j9644Gj03fuLpTUdrqYFL3P6OXoDxfPw

### CREATE ORDER
POST http://localhost:8080/client/order HTTP/1.1
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQyOTg4NjQsImV4cCI6MTcxNDMwMjQ2NH0.fL1jAQSCuq_j9644Gj03fuLpTUdrqYFL3P6OXoDxfPw
{
    "carWashID": 3,
    "service": [1, 2]
}

### GET SERVICES BY CARWASH AND STRING
GET http://localhost:8080/admin/carwash/services?searchString=&carWashID=4&pageNumber=1&limit=10 HTTP/1.1
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQyOTg4NjQsImV4cCI6MTcxNDMwMjQ2NH0.fL1jAQSCuq_j9644Gj03fuLpTUdrqYFL3P6OXoDxfPw

### CREATE SERVICE
POST http://localhost:8080/admin/carwash/services HTTP/1.1
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQyOTg4NjQsImV4cCI6MTcxNDMwMjQ2NH0.fL1jAQSCuq_j9644Gj03fuLpTUdrqYFL3P6OXoDxfPw

{
    "carWashID": 4,
    "name": "Service 2",
    "price": 100,
    "active": true
}

### UPDATE SERVICE
PATCH http://localhost:8080/admin/carwash/services HTTP/1.1
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQyOTg4NjQsImV4cCI6MTcxNDMwMjQ2NH0.fL1jAQSCuq_j9644Gj03fuLpTUdrqYFL3P6OXoDxfPw

{
    "id": 2,
    "name": "Service 1 modified",
    "price": 100,
    "active": true
}

### DELETE SERVICE
DELETE http://localhost:8080/admin/carwash/services HTTP/1.1
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQyOTg4NjQsImV4cCI6MTcxNDMwMjQ2NH0.fL1jAQSCuq_j9644Gj03fuLpTUdrqYFL3P6OXoDxfPw
    
{
    "id": 2
}

### GET USERS
GET http://localhost:8080/admin/carwash/users?searchString=&pageNumber=1&limit=10&carWashID=4 HTTP/1.1
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQzMDI0OTMsImV4cCI6MTcxNDMwNjA5M30.zif-PulBxBLPJMCLnvw4rY6vHPhNJhYejE-t9a0OWj4