POST http://localhost:8080/auth/login HTTP/1.1
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "1234"
}
###
GET http://localhost:8080/auth/logout HTTP/1.1
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQzOTQwODUsImV4cCI6MTcxNDM5NzY4NX0.UidzsOEgRyGIuIgjMLL3drv3BjjKs62RWmBz5l397Qs

###
POST http://localhost:8080/auth/register HTTP/1.1
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "1234",
    "fullName": "Test"
}
###
GET http://localhost:8080/client/carwash HTTP/1.1
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQzOTQwODUsImV4cCI6MTcxNDM5NzY4NX0.UidzsOEgRyGIuIgjMLL3drv3BjjKs62RWmBz5l397Qs
###
GET http://localhost:8080/client/carwash HTTP/1.1
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQzOTQwODUsImV4cCI6MTcxNDM5NzY4NX0.UidzsOEgRyGIuIgjMLL3drv3BjjKs62RWmBz5l397Qs

### CREATE CARWASH
POST http://localhost:8080/admin/carwash HTTP/1.1
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQzOTQwODUsImV4cCI6MTcxNDM5NzY4NX0.UidzsOEgRyGIuIgjMLL3drv3BjjKs62RWmBz5l397Qs

{
    "name": "CarWash4",
    "address": "Address",
    "latitude": 123.123,
    "longitude": 123.123,
    "active": true,
    "openTime": "08:00",
    "contact": "123456789"
}


### SEARCH CARWASH
GET http://localhost:8080/admin/carwash?searchString=&pageNumber=1&limit=10 HTTP/1.1
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQzMDI0OTMsImV4cCI6MTcxNDMwNjA5M30.zif-PulBxBLPJMCLnvw4rY6vHPhNJhYejE-t9a0OWj4

### UPDATE CARWASH
PATCH http://localhost:8080/admin/carwash HTTP/1.1
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQzOTQwODUsImV4cCI6MTcxNDM5NzY4NX0.UidzsOEgRyGIuIgjMLL3drv3BjjKs62RWmBz5l397Qs

{
    "id": 4,
    "active": false
}

### DELETE CARWASH
DELETE http://localhost:8080/admin/carwash HTTP/1.1
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQzOTQwODUsImV4cCI6MTcxNDM5NzY4NX0.UidzsOEgRyGIuIgjMLL3drv3BjjKs62RWmBz5l397Qs

{
    "id": 3
}

### GET SERVICES BY CARWASH
GET http://localhost:8080/client/service?carWashID=3
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQzOTQwODUsImV4cCI6MTcxNDM5NzY4NX0.UidzsOEgRyGIuIgjMLL3drv3BjjKs62RWmBz5l397Qs

### CREATE ORDER
POST http://localhost:8080/client/order HTTP/1.1
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQzOTQwODUsImV4cCI6MTcxNDM5NzY4NX0.UidzsOEgRyGIuIgjMLL3drv3BjjKs62RWmBz5l397Qs

{
    "carWashID": 3,
    "service": [1, 2]
}

### GET SERVICES BY CARWASH AND STRING
GET http://localhost:8080/admin/carwash/services?searchString=&carWashID=4&pageNumber=1&limit=10 HTTP/1.1
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQzOTQwODUsImV4cCI6MTcxNDM5NzY4NX0.UidzsOEgRyGIuIgjMLL3drv3BjjKs62RWmBz5l397Qs

### CREATE SERVICE
POST http://localhost:8080/admin/carwash/services HTTP/1.1
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQzOTQwODUsImV4cCI6MTcxNDM5NzY4NX0.UidzsOEgRyGIuIgjMLL3drv3BjjKs62RWmBz5l397Qs

{
    "carWashID": 4,
    "name": "Service 2",
    "price": 100,
    "active": true
}

### UPDATE SERVICE
PATCH http://localhost:8080/admin/carwash/services HTTP/1.1
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQzOTQwODUsImV4cCI6MTcxNDM5NzY4NX0.UidzsOEgRyGIuIgjMLL3drv3BjjKs62RWmBz5l397Qs

{
    "id": 2,
    "name": "Service 1 modified",
    "price": 100,
    "active": true
}

### DELETE SERVICE
DELETE http://localhost:8080/admin/carwash/services HTTP/1.1
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQzOTQwODUsImV4cCI6MTcxNDM5NzY4NX0.UidzsOEgRyGIuIgjMLL3drv3BjjKs62RWmBz5l397Qs

{
    "id": 2
}

### GET USERS
GET http://localhost:8080/admin/carwash/users?searchString=Client&pageNumber=1&limit=10&carWashID=5 HTTP/1.1
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQzOTc3NjQsImV4cCI6MTcxNDQwMTM2NH0.OMw79LjmZhyvcb2FezJ0WXZQmKJgYuUAgAV1VVATduI

### CREATE USER
POST http://localhost:8080/admin/carwash/users HTTP/1.1
Content-Type: application/json
Cookie: accessToken=eyJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJDYXJXYXNoIiwic3ViIjoidXNlciIsImlkIjoxLCJpYXQiOjE3MTQzOTc3NjQsImV4cCI6MTcxNDQwMTM2NH0.OMw79LjmZhyvcb2FezJ0WXZQmKJgYuUAgAV1VVATduI

{
    "carWashID": 5,
    "email": "sad@sadas.com",
    "password": "1234",
    "fullName": "Client",
    "role": "carwash",
    "active": true
}